packages:
  - "apps/*"
allowBuilds:
  '@clerk/shared': false
  esbuild: false
  msw: false
minimumReleaseAgeExclude:
  - '@remix-run/router@1.23.3'
  - react-router-dom@6.30.4
  - react-router@6.30.4
