filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    stream: all

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.ilm.enabled: false

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"

logging.level: info
