// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stores/{storeID}/zones": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "List zones by store",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store UUID",
                        "name": "storeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/zones.ZoneResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Create a zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store UUID",
                        "name": "storeID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Zone body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/zones.zoneRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/zones.ZoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stores/{storeID}/zones/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Get a zone by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store UUID",
                        "name": "storeID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Zone UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/zones.ZoneResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Update a zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store UUID",
                        "name": "storeID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Zone UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Zone body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/zones.zoneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/zones.ZoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "zones"
                ],
                "summary": "Delete a zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store UUID",
                        "name": "storeID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Zone UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/zones.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "zones.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "zone not found"
                }
            }
        },
        "zones.ZoneResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "example": 50
                },
                "color": {
                    "type": "string",
                    "example": "#6366f1"
                },
                "constraints": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string"
                },
                "height": {
                    "type": "number",
                    "example": 80
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "example": "Zone A"
                },
                "org_id": {
                    "type": "string"
                },
                "store_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "general",
                        "frozen",
                        "returns",
                        "staging",
                        "display",
                        "checkout"
                    ],
                    "example": "general"
                },
                "updated_at": {
                    "type": "string"
                },
                "width": {
                    "type": "number",
                    "example": 100
                },
                "x": {
                    "type": "number",
                    "example": 10
                },
                "y": {
                    "type": "number",
                    "example": 20
                }
            }
        },
        "zones.zoneRequest": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "color": {
                    "type": "string"
                },
                "constraints": {
                    "type": "object"
                },
                "height": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "general",
                        "frozen",
                        "returns",
                        "staging",
                        "display",
                        "checkout"
                    ]
                },
                "width": {
                    "type": "number"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "live-rack API",
	Description:      "Warehouse zoning, scanning, and analytics API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
