// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindUserRole = `-- name: BindUserRole :exec
INSERT INTO role_bindings (org_id, user_id, role_id)
SELECT $1, $2, r.id FROM roles r WHERE r.org_id = $1 AND r.name = $3
ON CONFLICT (user_id, role_id) DO NOTHING
`

type BindUserRoleParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) BindUserRole(ctx context.Context, arg BindUserRoleParams) error {
	_, err := q.db.Exec(ctx, bindUserRole, arg.OrgID, arg.UserID, arg.Name)
	return err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (org_id, idp_user_id, email, display_name, status)
VALUES ($1, $2, $3, $4, 'pending')
ON CONFLICT (idp_user_id) DO UPDATE
    SET email        = EXCLUDED.email,
        display_name = EXCLUDED.display_name,
        updated_at   = NOW()
RETURNING id, org_id, idp_user_id, email, display_name, avatar_url, created_at, updated_at, title, shift, status, mfa_enabled, last_seen_at
`

type CreateInvitedUserParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	IdpUserID   string    `json:"idp_user_id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createInvitedUser,
		arg.OrgID,
		arg.IdpUserID,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IdpUserID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Shift,
		&i.Status,
		&i.MfaEnabled,
		&i.LastSeenAt,
	)
	return i, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (org_id, name, address, lat, lon, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, address, lat, lon, timezone, created_at, updated_at
`

type CreateStoreParams struct {
	OrgID    uuid.UUID     `json:"org_id"`
	Name     string        `json:"name"`
	Address  pgtype.Text   `json:"address"`
	Lat      pgtype.Float8 `json:"lat"`
	Lon      pgtype.Float8 `json:"lon"`
	Timezone string        `json:"timezone"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.OrgID,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lon,
		arg.Timezone,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgByIdpID = `-- name: GetOrgByIdpID :one
SELECT id, idp_org_id, name, plan, created_at, updated_at FROM orgs WHERE idp_org_id = $1
`

func (q *Queries) GetOrgByIdpID(ctx context.Context, idpOrgID string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByIdpID, idpOrgID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.IdpOrgID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStore = `-- name: GetStore :one
SELECT id, org_id, name, address, lat, lon, timezone, created_at, updated_at FROM stores WHERE id = $1 AND org_id = $2
`

type GetStoreParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetStore(ctx context.Context, arg GetStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, getStore, arg.ID, arg.OrgID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdpID = `-- name: GetUserByIdpID :one
SELECT id, org_id, idp_user_id, email, display_name, avatar_url, created_at, updated_at, title, shift, status, mfa_enabled, last_seen_at FROM users WHERE idp_user_id = $1
`

func (q *Queries) GetUserByIdpID(ctx context.Context, idpUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdpID, idpUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IdpUserID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Shift,
		&i.Status,
		&i.MfaEnabled,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT r.name
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
WHERE rb.user_id = $1 AND rb.org_id = $2
LIMIT 1
`

type GetUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.UserID, arg.OrgID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUserStoreIDs = `-- name: GetUserStoreIDs :many
SELECT store_id FROM zone_scopes WHERE user_id = $1 AND org_id = $2
`

type GetUserStoreIDsParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) GetUserStoreIDs(ctx context.Context, arg GetUserStoreIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserStoreIDs, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var store_id uuid.UUID
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresByOrg = `-- name: ListStoresByOrg :many
SELECT id, org_id, name, address, lat, lon, timezone, created_at, updated_at FROM stores WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListStoresByOrg(ctx context.Context, orgID uuid.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStoresByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lon,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrg = `-- name: UpsertOrg :one
INSERT INTO orgs (idp_org_id, name, plan)
VALUES ($1, $2, $3)
ON CONFLICT (idp_org_id) DO UPDATE
    SET name = EXCLUDED.name, updated_at = NOW()
RETURNING id, idp_org_id, name, plan, created_at, updated_at
`

type UpsertOrgParams struct {
	IdpOrgID string `json:"idp_org_id"`
	Name     string `json:"name"`
	Plan     string `json:"plan"`
}

func (q *Queries) UpsertOrg(ctx context.Context, arg UpsertOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, upsertOrg, arg.IdpOrgID, arg.Name, arg.Plan)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.IdpOrgID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (org_id, idp_user_id, email, display_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (idp_user_id) DO UPDATE
    SET email        = COALESCE(NULLIF(EXCLUDED.email, ''), users.email),
        display_name = COALESCE(NULLIF(EXCLUDED.display_name, ''), users.display_name),
        avatar_url   = COALESCE(NULLIF(EXCLUDED.avatar_url, ''), users.avatar_url),
        status       = CASE WHEN users.status = 'pending' THEN 'active' ELSE users.status END,
        updated_at   = NOW()
RETURNING id, org_id, idp_user_id, email, display_name, avatar_url, created_at, updated_at, title, shift, status, mfa_enabled, last_seen_at
`

type UpsertUserParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	IdpUserID   string      `json:"idp_user_id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.OrgID,
		arg.IdpUserID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IdpUserID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Shift,
		&i.Status,
		&i.MfaEnabled,
		&i.LastSeenAt,
	)
	return i, err
}
