// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycle_counts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCycleCount = `-- name: CompleteCycleCount :one
UPDATE cycle_counts
SET status = 'completed', completed_at = NOW()
WHERE org_id = $1 AND id = $2 AND status = 'open'
RETURNING id, org_id, store_id, zone_id, status, created_by, created_at, completed_at
`

type CompleteCycleCountParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) CompleteCycleCount(ctx context.Context, arg CompleteCycleCountParams) (CycleCount, error) {
	row := q.db.QueryRow(ctx, completeCycleCount, arg.OrgID, arg.ID)
	var i CycleCount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createCycleCount = `-- name: CreateCycleCount :one
INSERT INTO cycle_counts (org_id, store_id, zone_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, store_id, zone_id, status, created_by, created_at, completed_at
`

type CreateCycleCountParams struct {
	OrgID     uuid.UUID   `json:"org_id"`
	StoreID   uuid.UUID   `json:"store_id"`
	ZoneID    uuid.UUID   `json:"zone_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCycleCount(ctx context.Context, arg CreateCycleCountParams) (CycleCount, error) {
	row := q.db.QueryRow(ctx, createCycleCount,
		arg.OrgID,
		arg.StoreID,
		arg.ZoneID,
		arg.CreatedBy,
	)
	var i CycleCount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCycleCount = `-- name: GetCycleCount :one
SELECT id, org_id, store_id, zone_id, status, created_by, created_at, completed_at FROM cycle_counts
WHERE org_id = $1 AND id = $2
`

type GetCycleCountParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetCycleCount(ctx context.Context, arg GetCycleCountParams) (CycleCount, error) {
	row := q.db.QueryRow(ctx, getCycleCount, arg.OrgID, arg.ID)
	var i CycleCount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCountLines = `-- name: ListCountLines :many
SELECT id, count_id, org_id, sku, system_qty, counted_qty FROM cycle_count_lines
WHERE count_id = $1
ORDER BY sku
`

func (q *Queries) ListCountLines(ctx context.Context, countID uuid.UUID) ([]CycleCountLine, error) {
	rows, err := q.db.Query(ctx, listCountLines, countID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CycleCountLine
	for rows.Next() {
		var i CycleCountLine
		if err := rows.Scan(
			&i.ID,
			&i.CountID,
			&i.OrgID,
			&i.Sku,
			&i.SystemQty,
			&i.CountedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCycleCountsByStore = `-- name: ListOpenCycleCountsByStore :many
SELECT id, org_id, store_id, zone_id, status, created_by, created_at, completed_at FROM cycle_counts
WHERE org_id = $1 AND store_id = $2 AND status = 'open'
ORDER BY created_at DESC
`

type ListOpenCycleCountsByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) ListOpenCycleCountsByStore(ctx context.Context, arg ListOpenCycleCountsByStoreParams) ([]CycleCount, error) {
	rows, err := q.db.Query(ctx, listOpenCycleCountsByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CycleCount
	for rows.Next() {
		var i CycleCount
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.ZoneID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCountedQty = `-- name: SetCountedQty :one
UPDATE cycle_count_lines
SET counted_qty = $1::int
WHERE org_id = $2 AND count_id = $3 AND sku = $4
RETURNING id, count_id, org_id, sku, system_qty, counted_qty
`

type SetCountedQtyParams struct {
	CountedQty int32     `json:"counted_qty"`
	OrgID      uuid.UUID `json:"org_id"`
	CountID    uuid.UUID `json:"count_id"`
	Sku        string    `json:"sku"`
}

func (q *Queries) SetCountedQty(ctx context.Context, arg SetCountedQtyParams) (CycleCountLine, error) {
	row := q.db.QueryRow(ctx, setCountedQty,
		arg.CountedQty,
		arg.OrgID,
		arg.CountID,
		arg.Sku,
	)
	var i CycleCountLine
	err := row.Scan(
		&i.ID,
		&i.CountID,
		&i.OrgID,
		&i.Sku,
		&i.SystemQty,
		&i.CountedQty,
	)
	return i, err
}

const snapshotCountLines = `-- name: SnapshotCountLines :exec
INSERT INTO cycle_count_lines (count_id, org_id, sku, system_qty)
SELECT $1, il.org_id, il.sku, il.qty
FROM item_locations il
WHERE il.org_id = $2 AND il.store_id = $3 AND il.zone_id = $4
`

type SnapshotCountLinesParams struct {
	CountID uuid.UUID `json:"count_id"`
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
	ZoneID  uuid.UUID `json:"zone_id"`
}

// Seed one line per SKU currently on-hand in the zone, capturing system_qty.
func (q *Queries) SnapshotCountLines(ctx context.Context, arg SnapshotCountLinesParams) error {
	_, err := q.db.Exec(ctx, snapshotCountLines,
		arg.CountID,
		arg.OrgID,
		arg.StoreID,
		arg.ZoneID,
	)
	return err
}
