// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integrations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getIntegration = `-- name: GetIntegration :one
SELECT id, org_id, kind, status, external_id, secret, config, created_at, updated_at FROM integrations
WHERE org_id = $1 AND kind = $2
`

type GetIntegrationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Kind  string    `json:"kind"`
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.OrgID, arg.Kind)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Status,
		&i.ExternalID,
		&i.Secret,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInboundWebhook = `-- name: InsertInboundWebhook :one
INSERT INTO webhooks_inbound (org_id, provider, event_id, topic, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, provider, event_id) DO NOTHING
RETURNING id, org_id, provider, event_id, topic, status, received_at
`

type InsertInboundWebhookParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	Provider string    `json:"provider"`
	EventID  string    `json:"event_id"`
	Topic    string    `json:"topic"`
	Status   string    `json:"status"`
}

func (q *Queries) InsertInboundWebhook(ctx context.Context, arg InsertInboundWebhookParams) (WebhooksInbound, error) {
	row := q.db.QueryRow(ctx, insertInboundWebhook,
		arg.OrgID,
		arg.Provider,
		arg.EventID,
		arg.Topic,
		arg.Status,
	)
	var i WebhooksInbound
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.EventID,
		&i.Topic,
		&i.Status,
		&i.ReceivedAt,
	)
	return i, err
}

const listInboundWebhooks = `-- name: ListInboundWebhooks :many
SELECT id, org_id, provider, event_id, topic, status, received_at FROM webhooks_inbound
WHERE org_id = $1
ORDER BY received_at DESC
LIMIT $2
`

type ListInboundWebhooksParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Limit int32     `json:"limit"`
}

func (q *Queries) ListInboundWebhooks(ctx context.Context, arg ListInboundWebhooksParams) ([]WebhooksInbound, error) {
	rows, err := q.db.Query(ctx, listInboundWebhooks, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhooksInbound
	for rows.Next() {
		var i WebhooksInbound
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.EventID,
			&i.Topic,
			&i.Status,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, org_id, kind, status, external_id, config, created_at, updated_at
FROM integrations
WHERE org_id = $1
ORDER BY kind
`

type ListIntegrationsRow struct {
	ID         uuid.UUID `json:"id"`
	OrgID      uuid.UUID `json:"org_id"`
	Kind       string    `json:"kind"`
	Status     string    `json:"status"`
	ExternalID string    `json:"external_id"`
	Config     []byte    `json:"config"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) ListIntegrations(ctx context.Context, orgID uuid.UUID) ([]ListIntegrationsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationsRow
	for rows.Next() {
		var i ListIntegrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Status,
			&i.ExternalID,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookStatus = `-- name: MarkWebhookStatus :exec
UPDATE webhooks_inbound
SET status = $3
WHERE org_id = $1 AND id = $2
`

type MarkWebhookStatusParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) MarkWebhookStatus(ctx context.Context, arg MarkWebhookStatusParams) error {
	_, err := q.db.Exec(ctx, markWebhookStatus, arg.OrgID, arg.ID, arg.Status)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :one
INSERT INTO integrations (org_id, kind, status, external_id, secret, config)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id, kind) DO UPDATE
SET status = EXCLUDED.status, external_id = EXCLUDED.external_id,
    secret = EXCLUDED.secret, config = EXCLUDED.config
RETURNING id, org_id, kind, status, external_id, secret, config, created_at, updated_at
`

type UpsertIntegrationParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	Kind       string    `json:"kind"`
	Status     string    `json:"status"`
	ExternalID string    `json:"external_id"`
	Secret     string    `json:"secret"`
	Config     []byte    `json:"config"`
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, upsertIntegration,
		arg.OrgID,
		arg.Kind,
		arg.Status,
		arg.ExternalID,
		arg.Secret,
		arg.Config,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Status,
		&i.ExternalID,
		&i.Secret,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
