// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getItemBySKU = `-- name: GetItemBySKU :one
SELECT id, org_id, sku, name, category, status, created_at, updated_at, reorder_point, price_cents FROM items
WHERE org_id = $1 AND sku = $2
`

type GetItemBySKUParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Sku   string    `json:"sku"`
}

func (q *Queries) GetItemBySKU(ctx context.Context, arg GetItemBySKUParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemBySKU, arg.OrgID, arg.Sku)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReorderPoint,
		&i.PriceCents,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, org_id, sku, name, category, status, created_at, updated_at, reorder_point, price_cents FROM items
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListItems(ctx context.Context, orgID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReorderPoint,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET name = $1, category = $2, status = $3,
    reorder_point = $4::int, price_cents = $5::int
WHERE org_id = $6 AND sku = $7
RETURNING id, org_id, sku, name, category, status, created_at, updated_at, reorder_point, price_cents
`

type UpdateItemParams struct {
	Name         string    `json:"name"`
	Category     string    `json:"category"`
	Status       string    `json:"status"`
	ReorderPoint int32     `json:"reorder_point"`
	PriceCents   int32     `json:"price_cents"`
	OrgID        uuid.UUID `json:"org_id"`
	Sku          string    `json:"sku"`
}

// Edit master-catalog fields for an existing SKU (LR-310).
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Name,
		arg.Category,
		arg.Status,
		arg.ReorderPoint,
		arg.PriceCents,
		arg.OrgID,
		arg.Sku,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReorderPoint,
		&i.PriceCents,
	)
	return i, err
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items (org_id, sku, name, category, status, reorder_point, price_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (org_id, sku) DO UPDATE
SET name = EXCLUDED.name, category = EXCLUDED.category,
    status = EXCLUDED.status, reorder_point = EXCLUDED.reorder_point,
    price_cents = EXCLUDED.price_cents
RETURNING id, org_id, sku, name, category, status, created_at, updated_at, reorder_point, price_cents
`

type UpsertItemParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	Sku          string    `json:"sku"`
	Name         string    `json:"name"`
	Category     string    `json:"category"`
	Status       string    `json:"status"`
	ReorderPoint int32     `json:"reorder_point"`
	PriceCents   int32     `json:"price_cents"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, upsertItem,
		arg.OrgID,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.Status,
		arg.ReorderPoint,
		arg.PriceCents,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReorderPoint,
		&i.PriceCents,
	)
	return i, err
}
