// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getItemBySKU = `-- name: GetItemBySKU :one
SELECT id, org_id, sku, name, category, status, created_at, updated_at FROM items
WHERE org_id = $1 AND sku = $2
`

type GetItemBySKUParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Sku   string    `json:"sku"`
}

func (q *Queries) GetItemBySKU(ctx context.Context, arg GetItemBySKUParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemBySKU, arg.OrgID, arg.Sku)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, org_id, sku, name, category, status, created_at, updated_at FROM items
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListItems(ctx context.Context, orgID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items (org_id, sku, name, category, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, sku) DO UPDATE
SET name = EXCLUDED.name, category = EXCLUDED.category, status = EXCLUDED.status
RETURNING id, org_id, sku, name, category, status, created_at, updated_at
`

type UpsertItemParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	Sku      string    `json:"sku"`
	Name     string    `json:"name"`
	Category string    `json:"category"`
	Status   string    `json:"status"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, upsertItem,
		arg.OrgID,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.Status,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
