// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_locations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adjustItemLocationQty = `-- name: AdjustItemLocationQty :one
INSERT INTO item_locations (org_id, store_id, zone_id, sku, qty)
VALUES ($1, $2, $3, $4, GREATEST($5::int, 0))
ON CONFLICT (org_id, zone_id, sku) DO UPDATE
SET qty = GREATEST(item_locations.qty + $5::int, 0)
RETURNING id, org_id, store_id, zone_id, sku, qty, updated_at
`

type AdjustItemLocationQtyParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
	ZoneID  uuid.UUID `json:"zone_id"`
	Sku     string    `json:"sku"`
	Qty     int32     `json:"qty"`
}

func (q *Queries) AdjustItemLocationQty(ctx context.Context, arg AdjustItemLocationQtyParams) (ItemLocation, error) {
	row := q.db.QueryRow(ctx, adjustItemLocationQty,
		arg.OrgID,
		arg.StoreID,
		arg.ZoneID,
		arg.Sku,
		arg.Qty,
	)
	var i ItemLocation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Sku,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementItemLocationQty = `-- name: DecrementItemLocationQty :one
UPDATE item_locations
SET qty = qty - $1::int
WHERE org_id = $2 AND zone_id = $3 AND sku = $4
  AND qty >= $1::int
RETURNING id, org_id, store_id, zone_id, sku, qty, updated_at
`

type DecrementItemLocationQtyParams struct {
	Qty    int32     `json:"qty"`
	OrgID  uuid.UUID `json:"org_id"`
	ZoneID uuid.UUID `json:"zone_id"`
	Sku    string    `json:"sku"`
}

// Guarded source decrement for a transfer: only succeeds when the location
// holds at least @qty. Returns no rows (pgx.ErrNoRows) when stock is
// insufficient or the location is missing, which the caller maps to 409.
func (q *Queries) DecrementItemLocationQty(ctx context.Context, arg DecrementItemLocationQtyParams) (ItemLocation, error) {
	row := q.db.QueryRow(ctx, decrementItemLocationQty,
		arg.Qty,
		arg.OrgID,
		arg.ZoneID,
		arg.Sku,
	)
	var i ItemLocation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Sku,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryByStore = `-- name: ListInventoryByStore :many
SELECT
    il.id,
    il.org_id,
    il.store_id,
    il.zone_id,
    il.sku,
    il.qty,
    il.updated_at,
    COALESCE(i.name, '')      AS name,
    COALESCE(i.category, '')  AS category,
    COALESCE(i.status, '')    AS status,
    COALESCE(i.reorder_point, 0)::int AS reorder_point,
    COALESCE((
        SELECT count(*) FROM scan_events se
        WHERE se.org_id = il.org_id AND se.zone_id = il.zone_id AND se.sku = il.sku
          AND se.action = 'pick' AND se.valid
          AND se.ts >= NOW() - INTERVAL '7 days'
    ), 0)::int  AS picks_7d,
    COALESCE((
        SELECT count(*) FROM scan_events se
        WHERE se.org_id = il.org_id AND se.zone_id = il.zone_id AND se.sku = il.sku
          AND se.action = 'pick' AND se.valid
          AND se.ts >= NOW() - INTERVAL '30 days'
    ), 0)::int  AS picks_30d
FROM item_locations il
LEFT JOIN items i ON i.org_id = il.org_id AND i.sku = il.sku
WHERE il.org_id = $1 AND il.store_id = $2
ORDER BY il.updated_at DESC
`

type ListInventoryByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

type ListInventoryByStoreRow struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	StoreID      uuid.UUID `json:"store_id"`
	ZoneID       uuid.UUID `json:"zone_id"`
	Sku          string    `json:"sku"`
	Qty          int32     `json:"qty"`
	UpdatedAt    time.Time `json:"updated_at"`
	Name         string    `json:"name"`
	Category     string    `json:"category"`
	Status       string    `json:"status"`
	ReorderPoint int32     `json:"reorder_point"`
	Picks7d      int32     `json:"picks_7d"`
	Picks30d     int32     `json:"picks_30d"`
}

func (q *Queries) ListInventoryByStore(ctx context.Context, arg ListInventoryByStoreParams) ([]ListInventoryByStoreRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryByStoreRow
	for rows.Next() {
		var i ListInventoryByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.ZoneID,
			&i.Sku,
			&i.Qty,
			&i.UpdatedAt,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.ReorderPoint,
			&i.Picks7d,
			&i.Picks30d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemLocationsBySKU = `-- name: ListItemLocationsBySKU :many
SELECT
    il.zone_id,
    il.qty,
    il.updated_at,
    COALESCE(z.name, '') AS zone_name
FROM item_locations il
LEFT JOIN zones z ON z.id = il.zone_id AND z.org_id = il.org_id
WHERE il.org_id = $1 AND il.store_id = $2 AND il.sku = $3
ORDER BY il.qty DESC
`

type ListItemLocationsBySKUParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
	Sku     string    `json:"sku"`
}

type ListItemLocationsBySKURow struct {
	ZoneID    uuid.UUID `json:"zone_id"`
	Qty       int32     `json:"qty"`
	UpdatedAt time.Time `json:"updated_at"`
	ZoneName  string    `json:"zone_name"`
}

// Per-zone on-hand for a single SKU across a store (item detail drawer).
func (q *Queries) ListItemLocationsBySKU(ctx context.Context, arg ListItemLocationsBySKUParams) ([]ListItemLocationsBySKURow, error) {
	rows, err := q.db.Query(ctx, listItemLocationsBySKU, arg.OrgID, arg.StoreID, arg.Sku)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemLocationsBySKURow
	for rows.Next() {
		var i ListItemLocationsBySKURow
		if err := rows.Scan(
			&i.ZoneID,
			&i.Qty,
			&i.UpdatedAt,
			&i.ZoneName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
