// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_locations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adjustItemLocationQty = `-- name: AdjustItemLocationQty :one
INSERT INTO item_locations (org_id, store_id, zone_id, sku, qty)
VALUES ($1, $2, $3, $4, GREATEST($5, 0))
ON CONFLICT (org_id, zone_id, sku) DO UPDATE
SET qty = GREATEST(item_locations.qty + $5, 0)
RETURNING id, org_id, store_id, zone_id, sku, qty, updated_at
`

type AdjustItemLocationQtyParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
	ZoneID  uuid.UUID `json:"zone_id"`
	Sku     string    `json:"sku"`
	Qty     int32     `json:"qty"`
}

func (q *Queries) AdjustItemLocationQty(ctx context.Context, arg AdjustItemLocationQtyParams) (ItemLocation, error) {
	row := q.db.QueryRow(ctx, adjustItemLocationQty,
		arg.OrgID,
		arg.StoreID,
		arg.ZoneID,
		arg.Sku,
		arg.Qty,
	)
	var i ItemLocation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Sku,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryByStore = `-- name: ListInventoryByStore :many
SELECT
    il.id,
    il.org_id,
    il.store_id,
    il.zone_id,
    il.sku,
    il.qty,
    il.updated_at,
    COALESCE(i.name, '')     AS name,
    COALESCE(i.category, '') AS category,
    COALESCE(i.status, '')   AS status
FROM item_locations il
LEFT JOIN items i ON i.org_id = il.org_id AND i.sku = il.sku
WHERE il.org_id = $1 AND il.store_id = $2
ORDER BY il.updated_at DESC
`

type ListInventoryByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

type ListInventoryByStoreRow struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	StoreID   uuid.UUID `json:"store_id"`
	ZoneID    uuid.UUID `json:"zone_id"`
	Sku       string    `json:"sku"`
	Qty       int32     `json:"qty"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	Category  string    `json:"category"`
	Status    string    `json:"status"`
}

func (q *Queries) ListInventoryByStore(ctx context.Context, arg ListInventoryByStoreParams) ([]ListInventoryByStoreRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryByStoreRow
	for rows.Next() {
		var i ListInventoryByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.ZoneID,
			&i.Sku,
			&i.Qty,
			&i.UpdatedAt,
			&i.Name,
			&i.Category,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
