// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ZoneType string

const (
	ZoneTypeGeneral  ZoneType = "general"
	ZoneTypeFrozen   ZoneType = "frozen"
	ZoneTypeReturns  ZoneType = "returns"
	ZoneTypeStaging  ZoneType = "staging"
	ZoneTypeDisplay  ZoneType = "display"
	ZoneTypeCheckout ZoneType = "checkout"
)

func (e *ZoneType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ZoneType(s)
	case string:
		*e = ZoneType(s)
	default:
		return fmt.Errorf("unsupported scan type for ZoneType: %T", src)
	}
	return nil
}

type NullZoneType struct {
	ZoneType ZoneType `json:"zone_type"`
	Valid    bool     `json:"valid"` // Valid is true if ZoneType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullZoneType) Scan(value interface{}) error {
	if value == nil {
		ns.ZoneType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ZoneType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullZoneType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ZoneType), nil
}

type Item struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Sku       string    `json:"sku"`
	Name      string    `json:"name"`
	Category  string    `json:"category"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ItemLocation struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	StoreID   uuid.UUID `json:"store_id"`
	ZoneID    uuid.UUID `json:"zone_id"`
	Sku       string    `json:"sku"`
	Qty       int32     `json:"qty"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Org struct {
	ID        uuid.UUID `json:"id"`
	IdpOrgID  string    `json:"idp_org_id"`
	Name      string    `json:"name"`
	Plan      string    `json:"plan"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Role struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

type RoleBinding struct {
	ID     uuid.UUID `json:"id"`
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type ScanEvent struct {
	ID        uuid.UUID `json:"id"`
	Ts        time.Time `json:"ts"`
	OrgID     uuid.UUID `json:"org_id"`
	StoreID   uuid.UUID `json:"store_id"`
	ZoneID    uuid.UUID `json:"zone_id"`
	ScannerID string    `json:"scanner_id"`
	Sku       string    `json:"sku"`
	Action    string    `json:"action"`
	Valid     bool      `json:"valid"`
	Reason    string    `json:"reason"`
}

type Store struct {
	ID        uuid.UUID     `json:"id"`
	OrgID     uuid.UUID     `json:"org_id"`
	Name      string        `json:"name"`
	Address   pgtype.Text   `json:"address"`
	Lat       pgtype.Float8 `json:"lat"`
	Lon       pgtype.Float8 `json:"lon"`
	Timezone  string        `json:"timezone"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID   `json:"id"`
	OrgID       uuid.UUID   `json:"org_id"`
	IdpUserID   string      `json:"idp_user_id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Zone struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	StoreID     uuid.UUID `json:"store_id"`
	Name        string    `json:"name"`
	Type        ZoneType  `json:"type"`
	X           float64   `json:"x"`
	Y           float64   `json:"y"`
	Width       float64   `json:"width"`
	Height      float64   `json:"height"`
	Color       string    `json:"color"`
	Capacity    int32     `json:"capacity"`
	Constraints []byte    `json:"constraints"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ZoneScope struct {
	ID      uuid.UUID `json:"id"`
	OrgID   uuid.UUID `json:"org_id"`
	UserID  uuid.UUID `json:"user_id"`
	StoreID uuid.UUID `json:"store_id"`
}
