// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pick_lists.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPickLine = `-- name: AddPickLine :one
INSERT INTO pick_list_lines (list_id, org_id, zone_id, sku, qty_requested, seq)
VALUES ($1, $2, $3, $4, $5::int, $6::int)
RETURNING id, list_id, org_id, zone_id, sku, qty_requested, qty_picked, seq, status
`

type AddPickLineParams struct {
	ListID       uuid.UUID   `json:"list_id"`
	OrgID        uuid.UUID   `json:"org_id"`
	ZoneID       pgtype.UUID `json:"zone_id"`
	Sku          string      `json:"sku"`
	QtyRequested int32       `json:"qty_requested"`
	Seq          int32       `json:"seq"`
}

func (q *Queries) AddPickLine(ctx context.Context, arg AddPickLineParams) (PickListLine, error) {
	row := q.db.QueryRow(ctx, addPickLine,
		arg.ListID,
		arg.OrgID,
		arg.ZoneID,
		arg.Sku,
		arg.QtyRequested,
		arg.Seq,
	)
	var i PickListLine
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.OrgID,
		&i.ZoneID,
		&i.Sku,
		&i.QtyRequested,
		&i.QtyPicked,
		&i.Seq,
		&i.Status,
	)
	return i, err
}

const cancelPickList = `-- name: CancelPickList :one
UPDATE pick_lists
SET status = 'cancelled'
WHERE org_id = $1 AND id = $2 AND status IN ('open', 'picking')
RETURNING id, org_id, store_id, reference, status, created_by, assignee_id, created_at, completed_at, wave_id
`

type CancelPickListParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) CancelPickList(ctx context.Context, arg CancelPickListParams) (PickList, error) {
	row := q.db.QueryRow(ctx, cancelPickList, arg.OrgID, arg.ID)
	var i PickList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.WaveID,
	)
	return i, err
}

const completePickList = `-- name: CompletePickList :one
UPDATE pick_lists
SET status = 'completed', completed_at = NOW()
WHERE org_id = $1 AND id = $2 AND status IN ('open', 'picking')
RETURNING id, org_id, store_id, reference, status, created_by, assignee_id, created_at, completed_at, wave_id
`

type CompletePickListParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) CompletePickList(ctx context.Context, arg CompletePickListParams) (PickList, error) {
	row := q.db.QueryRow(ctx, completePickList, arg.OrgID, arg.ID)
	var i PickList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.WaveID,
	)
	return i, err
}

const createPickList = `-- name: CreatePickList :one
INSERT INTO pick_lists (org_id, store_id, reference, created_by, assignee_id, status)
VALUES ($1, $2, $3, $4, $5, 'open')
RETURNING id, org_id, store_id, reference, status, created_by, assignee_id, created_at, completed_at, wave_id
`

type CreatePickListParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	StoreID    uuid.UUID   `json:"store_id"`
	Reference  string      `json:"reference"`
	CreatedBy  pgtype.UUID `json:"created_by"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

func (q *Queries) CreatePickList(ctx context.Context, arg CreatePickListParams) (PickList, error) {
	row := q.db.QueryRow(ctx, createPickList,
		arg.OrgID,
		arg.StoreID,
		arg.Reference,
		arg.CreatedBy,
		arg.AssigneeID,
	)
	var i PickList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.WaveID,
	)
	return i, err
}

const getPickList = `-- name: GetPickList :one
SELECT id, org_id, store_id, reference, status, created_by, assignee_id, created_at, completed_at, wave_id FROM pick_lists
WHERE org_id = $1 AND id = $2
`

type GetPickListParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetPickList(ctx context.Context, arg GetPickListParams) (PickList, error) {
	row := q.db.QueryRow(ctx, getPickList, arg.OrgID, arg.ID)
	var i PickList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.WaveID,
	)
	return i, err
}

const listPickListLines = `-- name: ListPickListLines :many
SELECT
    pl.id,
    pl.zone_id,
    pl.sku,
    pl.qty_requested,
    pl.qty_picked,
    pl.seq,
    pl.status,
    COALESCE(z.name, '')   AS zone_name,
    COALESCE(z.x, 0)::float8 AS zone_x,
    COALESCE(z.y, 0)::float8 AS zone_y
FROM pick_list_lines pl
LEFT JOIN zones z ON z.id = pl.zone_id AND z.org_id = pl.org_id
WHERE pl.list_id = $1
ORDER BY pl.seq
`

type ListPickListLinesRow struct {
	ID           uuid.UUID   `json:"id"`
	ZoneID       pgtype.UUID `json:"zone_id"`
	Sku          string      `json:"sku"`
	QtyRequested int32       `json:"qty_requested"`
	QtyPicked    int32       `json:"qty_picked"`
	Seq          int32       `json:"seq"`
	Status       string      `json:"status"`
	ZoneName     string      `json:"zone_name"`
	ZoneX        float64     `json:"zone_x"`
	ZoneY        float64     `json:"zone_y"`
}

func (q *Queries) ListPickListLines(ctx context.Context, listID uuid.UUID) ([]ListPickListLinesRow, error) {
	rows, err := q.db.Query(ctx, listPickListLines, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPickListLinesRow
	for rows.Next() {
		var i ListPickListLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Sku,
			&i.QtyRequested,
			&i.QtyPicked,
			&i.Seq,
			&i.Status,
			&i.ZoneName,
			&i.ZoneX,
			&i.ZoneY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickListsByStore = `-- name: ListPickListsByStore :many
SELECT
    pl.id, pl.org_id, pl.store_id, pl.reference, pl.status, pl.created_by, pl.assignee_id, pl.created_at, pl.completed_at, pl.wave_id,
    (SELECT count(*) FROM pick_list_lines l WHERE l.list_id = pl.id)::int AS line_count,
    (SELECT count(*) FROM pick_list_lines l WHERE l.list_id = pl.id AND l.status <> 'pending')::int AS done_count
FROM pick_lists pl
WHERE pl.org_id = $1 AND pl.store_id = $2
ORDER BY pl.created_at DESC
`

type ListPickListsByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

type ListPickListsByStoreRow struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	StoreID     uuid.UUID          `json:"store_id"`
	Reference   string             `json:"reference"`
	Status      string             `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	WaveID      pgtype.UUID        `json:"wave_id"`
	LineCount   int32              `json:"line_count"`
	DoneCount   int32              `json:"done_count"`
}

func (q *Queries) ListPickListsByStore(ctx context.Context, arg ListPickListsByStoreParams) ([]ListPickListsByStoreRow, error) {
	rows, err := q.db.Query(ctx, listPickListsByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPickListsByStoreRow
	for rows.Next() {
		var i ListPickListsByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.Reference,
			&i.Status,
			&i.CreatedBy,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.WaveID,
			&i.LineCount,
			&i.DoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePickSource = `-- name: ResolvePickSource :one
SELECT
    il.zone_id,
    il.qty,
    COALESCE(z.x, 0)::float8  AS zone_x,
    COALESCE(z.y, 0)::float8  AS zone_y,
    COALESCE(z.name, '')      AS zone_name
FROM item_locations il
LEFT JOIN zones z ON z.id = il.zone_id AND z.org_id = il.org_id
WHERE il.org_id = $1 AND il.store_id = $2 AND il.sku = $3 AND il.qty > 0
ORDER BY il.qty DESC
LIMIT 1
`

type ResolvePickSourceParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
	Sku     string    `json:"sku"`
}

type ResolvePickSourceRow struct {
	ZoneID   uuid.UUID `json:"zone_id"`
	Qty      int32     `json:"qty"`
	ZoneX    float64   `json:"zone_x"`
	ZoneY    float64   `json:"zone_y"`
	ZoneName string    `json:"zone_name"`
}

// Best source location for a SKU: the zone holding the most on-hand units, with
// its map coordinates so the route can be optimised. Returns no rows when the
// SKU has zero on-hand anywhere in the store.
func (q *Queries) ResolvePickSource(ctx context.Context, arg ResolvePickSourceParams) (ResolvePickSourceRow, error) {
	row := q.db.QueryRow(ctx, resolvePickSource, arg.OrgID, arg.StoreID, arg.Sku)
	var i ResolvePickSourceRow
	err := row.Scan(
		&i.ZoneID,
		&i.Qty,
		&i.ZoneX,
		&i.ZoneY,
		&i.ZoneName,
	)
	return i, err
}

const setPickLinePicked = `-- name: SetPickLinePicked :one
UPDATE pick_list_lines
SET qty_picked = $1::int, status = $2::text
WHERE org_id = $3 AND id = $4
RETURNING id, list_id, org_id, zone_id, sku, qty_requested, qty_picked, seq, status
`

type SetPickLinePickedParams struct {
	QtyPicked int32     `json:"qty_picked"`
	Status    string    `json:"status"`
	OrgID     uuid.UUID `json:"org_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetPickLinePicked(ctx context.Context, arg SetPickLinePickedParams) (PickListLine, error) {
	row := q.db.QueryRow(ctx, setPickLinePicked,
		arg.QtyPicked,
		arg.Status,
		arg.OrgID,
		arg.ID,
	)
	var i PickListLine
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.OrgID,
		&i.ZoneID,
		&i.Sku,
		&i.QtyRequested,
		&i.QtyPicked,
		&i.Seq,
		&i.Status,
	)
	return i, err
}

const startPickList = `-- name: StartPickList :one
UPDATE pick_lists
SET status = 'picking'
WHERE org_id = $1 AND id = $2 AND status = 'open'
RETURNING id, org_id, store_id, reference, status, created_by, assignee_id, created_at, completed_at, wave_id
`

type StartPickListParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) StartPickList(ctx context.Context, arg StartPickListParams) (PickList, error) {
	row := q.db.QueryRow(ctx, startPickList, arg.OrgID, arg.ID)
	var i PickList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.WaveID,
	)
	return i, err
}
