// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipelines.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO pipeline_cards (org_id, pipeline_id, stage_position, title, sku, priority, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, pipeline_id, stage_position, title, sku, priority, owner_id, entered_stage_at, created_at, updated_at
`

type CreateCardParams struct {
	OrgID         uuid.UUID   `json:"org_id"`
	PipelineID    uuid.UUID   `json:"pipeline_id"`
	StagePosition int32       `json:"stage_position"`
	Title         string      `json:"title"`
	Sku           string      `json:"sku"`
	Priority      string      `json:"priority"`
	OwnerID       pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (PipelineCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.OrgID,
		arg.PipelineID,
		arg.StagePosition,
		arg.Title,
		arg.Sku,
		arg.Priority,
		arg.OwnerID,
	)
	var i PipelineCard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PipelineID,
		&i.StagePosition,
		&i.Title,
		&i.Sku,
		&i.Priority,
		&i.OwnerID,
		&i.EnteredStageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (org_id, store_id, key, name)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, store_id, key, name, created_at, updated_at
`

type CreatePipelineParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
	Key     string    `json:"key"`
	Name    string    `json:"name"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.OrgID,
		arg.StoreID,
		arg.Key,
		arg.Name,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStage = `-- name: CreateStage :one
INSERT INTO pipeline_stages (org_id, pipeline_id, position, name, sla_seconds)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, pipeline_id, position, name, sla_seconds
`

type CreateStageParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	PipelineID uuid.UUID `json:"pipeline_id"`
	Position   int32     `json:"position"`
	Name       string    `json:"name"`
	SlaSeconds int64     `json:"sla_seconds"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, createStage,
		arg.OrgID,
		arg.PipelineID,
		arg.Position,
		arg.Name,
		arg.SlaSeconds,
	)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PipelineID,
		&i.Position,
		&i.Name,
		&i.SlaSeconds,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT id, org_id, pipeline_id, stage_position, title, sku, priority, owner_id, entered_stage_at, created_at, updated_at FROM pipeline_cards
WHERE org_id = $1 AND id = $2
`

type GetCardParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (PipelineCard, error) {
	row := q.db.QueryRow(ctx, getCard, arg.OrgID, arg.ID)
	var i PipelineCard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PipelineID,
		&i.StagePosition,
		&i.Title,
		&i.Sku,
		&i.Priority,
		&i.OwnerID,
		&i.EnteredStageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, org_id, store_id, key, name, created_at, updated_at FROM pipelines
WHERE org_id = $1 AND id = $2
`

type GetPipelineParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetPipeline(ctx context.Context, arg GetPipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipeline, arg.OrgID, arg.ID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByPipeline = `-- name: ListCardsByPipeline :many
SELECT id, org_id, pipeline_id, stage_position, title, sku, priority, owner_id, entered_stage_at, created_at, updated_at FROM pipeline_cards
WHERE org_id = $1 AND pipeline_id = $2
ORDER BY stage_position, priority DESC, entered_stage_at
`

type ListCardsByPipelineParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	PipelineID uuid.UUID `json:"pipeline_id"`
}

func (q *Queries) ListCardsByPipeline(ctx context.Context, arg ListCardsByPipelineParams) ([]PipelineCard, error) {
	rows, err := q.db.Query(ctx, listCardsByPipeline, arg.OrgID, arg.PipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineCard
	for rows.Next() {
		var i PipelineCard
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PipelineID,
			&i.StagePosition,
			&i.Title,
			&i.Sku,
			&i.Priority,
			&i.OwnerID,
			&i.EnteredStageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByStore = `-- name: ListPipelinesByStore :many
SELECT id, org_id, store_id, key, name, created_at, updated_at FROM pipelines
WHERE org_id = $1 AND store_id = $2
ORDER BY created_at
`

type ListPipelinesByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) ListPipelinesByStore(ctx context.Context, arg ListPipelinesByStoreParams) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.Key,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagesByPipeline = `-- name: ListStagesByPipeline :many
SELECT id, org_id, pipeline_id, position, name, sla_seconds FROM pipeline_stages
WHERE org_id = $1 AND pipeline_id = $2
ORDER BY position
`

type ListStagesByPipelineParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	PipelineID uuid.UUID `json:"pipeline_id"`
}

func (q *Queries) ListStagesByPipeline(ctx context.Context, arg ListStagesByPipelineParams) ([]PipelineStage, error) {
	rows, err := q.db.Query(ctx, listStagesByPipeline, arg.OrgID, arg.PipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineStage
	for rows.Next() {
		var i PipelineStage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PipelineID,
			&i.Position,
			&i.Name,
			&i.SlaSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCard = `-- name: MoveCard :one
UPDATE pipeline_cards
SET stage_position = $3, entered_stage_at = NOW()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, pipeline_id, stage_position, title, sku, priority, owner_id, entered_stage_at, created_at, updated_at
`

type MoveCardParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	ID            uuid.UUID `json:"id"`
	StagePosition int32     `json:"stage_position"`
}

func (q *Queries) MoveCard(ctx context.Context, arg MoveCardParams) (PipelineCard, error) {
	row := q.db.QueryRow(ctx, moveCard, arg.OrgID, arg.ID, arg.StagePosition)
	var i PipelineCard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PipelineID,
		&i.StagePosition,
		&i.Title,
		&i.Sku,
		&i.Priority,
		&i.OwnerID,
		&i.EnteredStageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
