// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BindUserRole(ctx context.Context, arg BindUserRoleParams) error
	CountZonesByStore(ctx context.Context, arg CountZonesByStoreParams) (int64, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error)
	DeleteZone(ctx context.Context, arg DeleteZoneParams) error
	GetOrgByClerkID(ctx context.Context, clerkOrgID string) (Org, error)
	GetStore(ctx context.Context, arg GetStoreParams) (Store, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error)
	GetUserStoreIDs(ctx context.Context, arg GetUserStoreIDsParams) ([]uuid.UUID, error)
	GetZone(ctx context.Context, arg GetZoneParams) (Zone, error)
	ListStoresByOrg(ctx context.Context, orgID uuid.UUID) ([]Store, error)
	ListZonesByStore(ctx context.Context, arg ListZonesByStoreParams) ([]Zone, error)
	UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error)
	UpsertOrg(ctx context.Context, arg UpsertOrgParams) (Org, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
