// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSaleEvent = `-- name: CreateSaleEvent :one
INSERT INTO sales_events (ts, org_id, store_id, source, order_id, sku, qty, amount_cents, currency, channel)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, ts, org_id, store_id, source, order_id, sku, qty, amount_cents, currency, channel
`

type CreateSaleEventParams struct {
	Ts          time.Time   `json:"ts"`
	OrgID       uuid.UUID   `json:"org_id"`
	StoreID     pgtype.UUID `json:"store_id"`
	Source      string      `json:"source"`
	OrderID     string      `json:"order_id"`
	Sku         string      `json:"sku"`
	Qty         int32       `json:"qty"`
	AmountCents int64       `json:"amount_cents"`
	Currency    string      `json:"currency"`
	Channel     string      `json:"channel"`
}

func (q *Queries) CreateSaleEvent(ctx context.Context, arg CreateSaleEventParams) (SalesEvent, error) {
	row := q.db.QueryRow(ctx, createSaleEvent,
		arg.Ts,
		arg.OrgID,
		arg.StoreID,
		arg.Source,
		arg.OrderID,
		arg.Sku,
		arg.Qty,
		arg.AmountCents,
		arg.Currency,
		arg.Channel,
	)
	var i SalesEvent
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.OrgID,
		&i.StoreID,
		&i.Source,
		&i.OrderID,
		&i.Sku,
		&i.Qty,
		&i.AmountCents,
		&i.Currency,
		&i.Channel,
	)
	return i, err
}

const salesByDay = `-- name: SalesByDay :many
SELECT
    time_bucket('1 day', ts) AS day,
    COALESCE(SUM(amount_cents), 0)::BIGINT AS revenue_cents
FROM sales_events
WHERE org_id = $1 AND ts >= $2
GROUP BY day
ORDER BY day
`

type SalesByDayParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Ts    time.Time `json:"ts"`
}

type SalesByDayRow struct {
	Day          interface{} `json:"day"`
	RevenueCents int64       `json:"revenue_cents"`
}

func (q *Queries) SalesByDay(ctx context.Context, arg SalesByDayParams) ([]SalesByDayRow, error) {
	rows, err := q.db.Query(ctx, salesByDay, arg.OrgID, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesByDayRow
	for rows.Next() {
		var i SalesByDayRow
		if err := rows.Scan(&i.Day, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesSummary = `-- name: SalesSummary :one
SELECT
    COALESCE(SUM(amount_cents), 0)::BIGINT      AS revenue_cents,
    COALESCE(SUM(qty), 0)::BIGINT               AS units,
    COUNT(DISTINCT order_id)                    AS orders
FROM sales_events
WHERE org_id = $1 AND ts >= $2
`

type SalesSummaryParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Ts    time.Time `json:"ts"`
}

type SalesSummaryRow struct {
	RevenueCents int64 `json:"revenue_cents"`
	Units        int64 `json:"units"`
	Orders       int64 `json:"orders"`
}

func (q *Queries) SalesSummary(ctx context.Context, arg SalesSummaryParams) (SalesSummaryRow, error) {
	row := q.db.QueryRow(ctx, salesSummary, arg.OrgID, arg.Ts)
	var i SalesSummaryRow
	err := row.Scan(&i.RevenueCents, &i.Units, &i.Orders)
	return i, err
}
