// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_events.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScanEvent = `-- name: CreateScanEvent :one
INSERT INTO scan_events (ts, org_id, store_id, zone_id, scanner_id, sku, action, valid, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, ts, org_id, store_id, zone_id, scanner_id, sku, action, valid, reason
`

type CreateScanEventParams struct {
	Ts        time.Time `json:"ts"`
	OrgID     uuid.UUID `json:"org_id"`
	StoreID   uuid.UUID `json:"store_id"`
	ZoneID    uuid.UUID `json:"zone_id"`
	ScannerID string    `json:"scanner_id"`
	Sku       string    `json:"sku"`
	Action    string    `json:"action"`
	Valid     bool      `json:"valid"`
	Reason    string    `json:"reason"`
}

func (q *Queries) CreateScanEvent(ctx context.Context, arg CreateScanEventParams) (ScanEvent, error) {
	row := q.db.QueryRow(ctx, createScanEvent,
		arg.Ts,
		arg.OrgID,
		arg.StoreID,
		arg.ZoneID,
		arg.ScannerID,
		arg.Sku,
		arg.Action,
		arg.Valid,
		arg.Reason,
	)
	var i ScanEvent
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.ScannerID,
		&i.Sku,
		&i.Action,
		&i.Valid,
		&i.Reason,
	)
	return i, err
}

const getLastScanForSKU = `-- name: GetLastScanForSKU :one
SELECT id, ts, org_id, store_id, zone_id, scanner_id, sku, action, valid, reason FROM scan_events
WHERE org_id = $1 AND zone_id = $2 AND sku = $3
ORDER BY ts DESC
LIMIT 1
`

type GetLastScanForSKUParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	ZoneID uuid.UUID `json:"zone_id"`
	Sku    string    `json:"sku"`
}

func (q *Queries) GetLastScanForSKU(ctx context.Context, arg GetLastScanForSKUParams) (ScanEvent, error) {
	row := q.db.QueryRow(ctx, getLastScanForSKU, arg.OrgID, arg.ZoneID, arg.Sku)
	var i ScanEvent
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.ScannerID,
		&i.Sku,
		&i.Action,
		&i.Valid,
		&i.Reason,
	)
	return i, err
}

const listScanEventsByZone = `-- name: ListScanEventsByZone :many
SELECT id, ts, org_id, store_id, zone_id, scanner_id, sku, action, valid, reason FROM scan_events
WHERE org_id = $1 AND zone_id = $2
ORDER BY ts DESC
LIMIT $3
`

type ListScanEventsByZoneParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	ZoneID uuid.UUID `json:"zone_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListScanEventsByZone(ctx context.Context, arg ListScanEventsByZoneParams) ([]ScanEvent, error) {
	rows, err := q.db.Query(ctx, listScanEventsByZone, arg.OrgID, arg.ZoneID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanEvent
	for rows.Next() {
		var i ScanEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.OrgID,
			&i.StoreID,
			&i.ZoneID,
			&i.ScannerID,
			&i.Sku,
			&i.Action,
			&i.Valid,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
