// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const searchEntities = `-- name: SearchEntities :many
SELECT kind, id, label, sublabel, score
FROM (
    SELECT
        'item'::text AS kind,
        i.id         AS id,
        i.name       AS label,
        i.sku        AS sublabel,
        GREATEST(
            similarity(i.name, $1::text),
            similarity(i.sku, $1::text)
        )::real      AS score
    FROM items i
    WHERE i.org_id = $2
      AND (
          i.name % $1::text
          OR i.sku % $1::text
          OR i.name ILIKE '%' || $1::text || '%'
          OR i.sku ILIKE '%' || $1::text || '%'
      )

    UNION ALL

    SELECT
        'zone'::text                           AS kind,
        z.id                                   AS id,
        z.name                                 AS label,
        z.type::text                           AS sublabel,
        similarity(z.name, $1::text)::real AS score
    FROM zones z
    WHERE z.org_id = $2
      AND (
          z.name % $1::text
          OR z.name ILIKE '%' || $1::text || '%'
      )
) results
ORDER BY score DESC, label ASC
LIMIT $3::int
`

type SearchEntitiesParams struct {
	Query      string    `json:"query"`
	OrgID      uuid.UUID `json:"org_id"`
	MaxResults int32     `json:"max_results"`
}

type SearchEntitiesRow struct {
	Kind     string    `json:"kind"`
	ID       uuid.UUID `json:"id"`
	Label    string    `json:"label"`
	Sublabel string    `json:"sublabel"`
	Score    float32   `json:"score"`
}

// Fuzzy ⌘K search across items (sku + name) and zones (name) for one org.
// Trigram similarity ranks fuzzy hits; ILIKE catches short substrings GIN trigram
// can still serve. Results ordered by best score, capped by max_results.
func (q *Queries) SearchEntities(ctx context.Context, arg SearchEntitiesParams) ([]SearchEntitiesRow, error) {
	rows, err := q.db.Query(ctx, searchEntities, arg.Query, arg.OrgID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchEntitiesRow
	for rows.Next() {
		var i SearchEntitiesRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Label,
			&i.Sublabel,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
