// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addShipmentItem = `-- name: AddShipmentItem :one
INSERT INTO shipment_items (shipment_id, org_id, sku, qty)
VALUES ($1, $2, $3, $4::int)
RETURNING id, shipment_id, org_id, sku, qty
`

type AddShipmentItemParams struct {
	ShipmentID uuid.UUID `json:"shipment_id"`
	OrgID      uuid.UUID `json:"org_id"`
	Sku        string    `json:"sku"`
	Qty        int32     `json:"qty"`
}

func (q *Queries) AddShipmentItem(ctx context.Context, arg AddShipmentItemParams) (ShipmentItem, error) {
	row := q.db.QueryRow(ctx, addShipmentItem,
		arg.ShipmentID,
		arg.OrgID,
		arg.Sku,
		arg.Qty,
	)
	var i ShipmentItem
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.OrgID,
		&i.Sku,
		&i.Qty,
	)
	return i, err
}

const cancelShipment = `-- name: CancelShipment :one
UPDATE shipments
SET status = 'cancelled'
WHERE org_id = $1 AND id = $2 AND status IN ('packing', 'packed')
RETURNING id, org_id, store_id, pick_list_id, reference, carrier, tracking_number, status, created_by, created_at, dispatched_at
`

type CancelShipmentParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) CancelShipment(ctx context.Context, arg CancelShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, cancelShipment, arg.OrgID, arg.ID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.PickListID,
		&i.Reference,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DispatchedAt,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (org_id, store_id, pick_list_id, reference, created_by, status)
VALUES ($1, $2, $3, $4, $5, 'packing')
RETURNING id, org_id, store_id, pick_list_id, reference, carrier, tracking_number, status, created_by, created_at, dispatched_at
`

type CreateShipmentParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	StoreID    uuid.UUID   `json:"store_id"`
	PickListID pgtype.UUID `json:"pick_list_id"`
	Reference  string      `json:"reference"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.OrgID,
		arg.StoreID,
		arg.PickListID,
		arg.Reference,
		arg.CreatedBy,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.PickListID,
		&i.Reference,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DispatchedAt,
	)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, org_id, store_id, pick_list_id, reference, carrier, tracking_number, status, created_by, created_at, dispatched_at FROM shipments
WHERE org_id = $1 AND id = $2
`

type GetShipmentParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetShipment(ctx context.Context, arg GetShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipment, arg.OrgID, arg.ID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.PickListID,
		&i.Reference,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DispatchedAt,
	)
	return i, err
}

const listShipmentItems = `-- name: ListShipmentItems :many
SELECT id, sku, qty FROM shipment_items
WHERE shipment_id = $1
ORDER BY sku
`

type ListShipmentItemsRow struct {
	ID  uuid.UUID `json:"id"`
	Sku string    `json:"sku"`
	Qty int32     `json:"qty"`
}

func (q *Queries) ListShipmentItems(ctx context.Context, shipmentID uuid.UUID) ([]ListShipmentItemsRow, error) {
	rows, err := q.db.Query(ctx, listShipmentItems, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShipmentItemsRow
	for rows.Next() {
		var i ListShipmentItemsRow
		if err := rows.Scan(&i.ID, &i.Sku, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentsByStore = `-- name: ListShipmentsByStore :many
SELECT
    s.id, s.org_id, s.store_id, s.pick_list_id, s.reference, s.carrier, s.tracking_number, s.status, s.created_by, s.created_at, s.dispatched_at,
    (SELECT count(*) FROM shipment_items i WHERE i.shipment_id = s.id)::int AS item_count
FROM shipments s
WHERE s.org_id = $1 AND s.store_id = $2
ORDER BY s.created_at DESC
`

type ListShipmentsByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

type ListShipmentsByStoreRow struct {
	ID             uuid.UUID          `json:"id"`
	OrgID          uuid.UUID          `json:"org_id"`
	StoreID        uuid.UUID          `json:"store_id"`
	PickListID     pgtype.UUID        `json:"pick_list_id"`
	Reference      string             `json:"reference"`
	Carrier        string             `json:"carrier"`
	TrackingNumber string             `json:"tracking_number"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatched_at"`
	ItemCount      int32              `json:"item_count"`
}

func (q *Queries) ListShipmentsByStore(ctx context.Context, arg ListShipmentsByStoreParams) ([]ListShipmentsByStoreRow, error) {
	rows, err := q.db.Query(ctx, listShipmentsByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShipmentsByStoreRow
	for rows.Next() {
		var i ListShipmentsByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.PickListID,
			&i.Reference,
			&i.Carrier,
			&i.TrackingNumber,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShipmentDispatched = `-- name: MarkShipmentDispatched :one
UPDATE shipments
SET status = 'dispatched', carrier = $1, tracking_number = $2,
    dispatched_at = NOW()
WHERE org_id = $3 AND id = $4 AND status = 'packed'
RETURNING id, org_id, store_id, pick_list_id, reference, carrier, tracking_number, status, created_by, created_at, dispatched_at
`

type MarkShipmentDispatchedParams struct {
	Carrier        string    `json:"carrier"`
	TrackingNumber string    `json:"tracking_number"`
	OrgID          uuid.UUID `json:"org_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) MarkShipmentDispatched(ctx context.Context, arg MarkShipmentDispatchedParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, markShipmentDispatched,
		arg.Carrier,
		arg.TrackingNumber,
		arg.OrgID,
		arg.ID,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.PickListID,
		&i.Reference,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DispatchedAt,
	)
	return i, err
}

const markShipmentPacked = `-- name: MarkShipmentPacked :one
UPDATE shipments
SET status = 'packed'
WHERE org_id = $1 AND id = $2 AND status = 'packing'
RETURNING id, org_id, store_id, pick_list_id, reference, carrier, tracking_number, status, created_by, created_at, dispatched_at
`

type MarkShipmentPackedParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) MarkShipmentPacked(ctx context.Context, arg MarkShipmentPackedParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, markShipmentPacked, arg.OrgID, arg.ID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.PickListID,
		&i.Reference,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DispatchedAt,
	)
	return i, err
}
