// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignTask = `-- name: AssignTask :one
UPDATE tasks
SET assignee_id = $3
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, store_id, zone_id, title, status, priority, assignee_id, due_at, created_at, updated_at
`

type AssignTaskParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	ID         uuid.UUID   `json:"id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, assignTask, arg.OrgID, arg.ID, arg.AssigneeID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOpenTasksByTitle = `-- name: CountOpenTasksByTitle :one
SELECT count(*) FROM tasks
WHERE org_id = $1 AND store_id = $2 AND zone_id = $3
  AND title = $4 AND status <> 'done'
`

type CountOpenTasksByTitleParams struct {
	OrgID   uuid.UUID   `json:"org_id"`
	StoreID uuid.UUID   `json:"store_id"`
	ZoneID  pgtype.UUID `json:"zone_id"`
	Title   string      `json:"title"`
}

func (q *Queries) CountOpenTasksByTitle(ctx context.Context, arg CountOpenTasksByTitleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTasksByTitle,
		arg.OrgID,
		arg.StoreID,
		arg.ZoneID,
		arg.Title,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (org_id, store_id, zone_id, title, status, priority, assignee_id, due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, store_id, zone_id, title, status, priority, assignee_id, due_at, created_at, updated_at
`

type CreateTaskParams struct {
	OrgID      uuid.UUID          `json:"org_id"`
	StoreID    uuid.UUID          `json:"store_id"`
	ZoneID     pgtype.UUID        `json:"zone_id"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	Priority   string             `json:"priority"`
	AssigneeID pgtype.UUID        `json:"assignee_id"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.OrgID,
		arg.StoreID,
		arg.ZoneID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE org_id = $1 AND id = $2
`

type DeleteTaskParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.OrgID, arg.ID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, org_id, store_id, zone_id, title, status, priority, assignee_id, due_at, created_at, updated_at FROM tasks
WHERE org_id = $1 AND id = $2
`

type GetTaskParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.OrgID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByStore = `-- name: ListTasksByStore :many
SELECT id, org_id, store_id, zone_id, title, status, priority, assignee_id, due_at, created_at, updated_at FROM tasks
WHERE org_id = $1 AND store_id = $2
ORDER BY status, priority DESC, created_at
`

type ListTasksByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) ListTasksByStore(ctx context.Context, arg ListTasksByStoreParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.ZoneID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $3
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, store_id, zone_id, title, status, priority, assignee_id, due_at, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.OrgID, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.ZoneID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
