// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waves.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignListsToWave = `-- name: AssignListsToWave :exec
UPDATE pick_lists
SET wave_id = $1
WHERE org_id = $2 AND store_id = $3
  AND id = ANY($4::uuid[]) AND wave_id IS NULL
`

type AssignListsToWaveParams struct {
	WaveID  pgtype.UUID `json:"wave_id"`
	OrgID   uuid.UUID   `json:"org_id"`
	StoreID uuid.UUID   `json:"store_id"`
	ListIds []uuid.UUID `json:"list_ids"`
}

// Attach the given open pick lists to a wave (skips lists already in a wave).
func (q *Queries) AssignListsToWave(ctx context.Context, arg AssignListsToWaveParams) error {
	_, err := q.db.Exec(ctx, assignListsToWave,
		arg.WaveID,
		arg.OrgID,
		arg.StoreID,
		arg.ListIds,
	)
	return err
}

const completeWave = `-- name: CompleteWave :one
UPDATE waves
SET status = 'completed', completed_at = NOW()
WHERE org_id = $1 AND id = $2 AND status IN ('open', 'picking')
RETURNING id, org_id, store_id, reference, status, created_by, created_at, completed_at
`

type CompleteWaveParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) CompleteWave(ctx context.Context, arg CompleteWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, completeWave, arg.OrgID, arg.ID)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWave = `-- name: CreateWave :one
INSERT INTO waves (org_id, store_id, reference, created_by, status)
VALUES ($1, $2, $3, $4, 'open')
RETURNING id, org_id, store_id, reference, status, created_by, created_at, completed_at
`

type CreateWaveParams struct {
	OrgID     uuid.UUID   `json:"org_id"`
	StoreID   uuid.UUID   `json:"store_id"`
	Reference string      `json:"reference"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWave(ctx context.Context, arg CreateWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, createWave,
		arg.OrgID,
		arg.StoreID,
		arg.Reference,
		arg.CreatedBy,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWave = `-- name: GetWave :one
SELECT id, org_id, store_id, reference, status, created_by, created_at, completed_at FROM waves
WHERE org_id = $1 AND id = $2
`

type GetWaveParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetWave(ctx context.Context, arg GetWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, getWave, arg.OrgID, arg.ID)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listWaveMergedLines = `-- name: ListWaveMergedLines :many
SELECT
    pll.sku,
    pll.zone_id,
    COALESCE(z.name, '')     AS zone_name,
    COALESCE(z.x, 0)::float8 AS zone_x,
    COALESCE(z.y, 0)::float8 AS zone_y,
    SUM(pll.qty_requested)::int AS qty_requested,
    SUM(pll.qty_picked)::int    AS qty_picked,
    COUNT(*)::int               AS order_count
FROM pick_list_lines pll
JOIN pick_lists pl ON pl.id = pll.list_id AND pl.org_id = pll.org_id
LEFT JOIN zones z ON z.id = pll.zone_id AND z.org_id = pll.org_id
WHERE pl.org_id = $1 AND pl.wave_id = $2 AND pll.zone_id IS NOT NULL
GROUP BY pll.sku, pll.zone_id, z.name, z.x, z.y
ORDER BY pll.sku
`

type ListWaveMergedLinesParams struct {
	OrgID  uuid.UUID   `json:"org_id"`
	WaveID pgtype.UUID `json:"wave_id"`
}

type ListWaveMergedLinesRow struct {
	Sku          string      `json:"sku"`
	ZoneID       pgtype.UUID `json:"zone_id"`
	ZoneName     string      `json:"zone_name"`
	ZoneX        float64     `json:"zone_x"`
	ZoneY        float64     `json:"zone_y"`
	QtyRequested int32       `json:"qty_requested"`
	QtyPicked    int32       `json:"qty_picked"`
	OrderCount   int32       `json:"order_count"`
}

// Aggregate member order lines into one stop per SKU+zone, summing demand and
// picked qty across the wave's orders. Only mapped stops are returned.
func (q *Queries) ListWaveMergedLines(ctx context.Context, arg ListWaveMergedLinesParams) ([]ListWaveMergedLinesRow, error) {
	rows, err := q.db.Query(ctx, listWaveMergedLines, arg.OrgID, arg.WaveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWaveMergedLinesRow
	for rows.Next() {
		var i ListWaveMergedLinesRow
		if err := rows.Scan(
			&i.Sku,
			&i.ZoneID,
			&i.ZoneName,
			&i.ZoneX,
			&i.ZoneY,
			&i.QtyRequested,
			&i.QtyPicked,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaveStopMemberLines = `-- name: ListWaveStopMemberLines :many
SELECT pll.id, pll.list_id, pll.qty_requested, pll.qty_picked
FROM pick_list_lines pll
JOIN pick_lists pl ON pl.id = pll.list_id AND pl.org_id = pll.org_id
WHERE pl.org_id = $1 AND pl.wave_id = $2
  AND pll.sku = $3 AND pll.zone_id = $4
ORDER BY pl.created_at, pll.seq
`

type ListWaveStopMemberLinesParams struct {
	OrgID  uuid.UUID   `json:"org_id"`
	WaveID pgtype.UUID `json:"wave_id"`
	Sku    string      `json:"sku"`
	ZoneID pgtype.UUID `json:"zone_id"`
}

type ListWaveStopMemberLinesRow struct {
	ID           uuid.UUID `json:"id"`
	ListID       uuid.UUID `json:"list_id"`
	QtyRequested int32     `json:"qty_requested"`
	QtyPicked    int32     `json:"qty_picked"`
}

// Member order lines for one SKU+zone stop, in FIFO order (oldest order first),
// for allocating a merged picked quantity back to orders.
func (q *Queries) ListWaveStopMemberLines(ctx context.Context, arg ListWaveStopMemberLinesParams) ([]ListWaveStopMemberLinesRow, error) {
	rows, err := q.db.Query(ctx, listWaveStopMemberLines,
		arg.OrgID,
		arg.WaveID,
		arg.Sku,
		arg.ZoneID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWaveStopMemberLinesRow
	for rows.Next() {
		var i ListWaveStopMemberLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.QtyRequested,
			&i.QtyPicked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWavesByStore = `-- name: ListWavesByStore :many
SELECT
    w.id, w.org_id, w.store_id, w.reference, w.status, w.created_by, w.created_at, w.completed_at,
    (SELECT count(*) FROM pick_lists pl WHERE pl.wave_id = w.id)::int AS list_count
FROM waves w
WHERE w.org_id = $1 AND w.store_id = $2
ORDER BY w.created_at DESC
`

type ListWavesByStoreParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	StoreID uuid.UUID `json:"store_id"`
}

type ListWavesByStoreRow struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	StoreID     uuid.UUID          `json:"store_id"`
	Reference   string             `json:"reference"`
	Status      string             `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ListCount   int32              `json:"list_count"`
}

func (q *Queries) ListWavesByStore(ctx context.Context, arg ListWavesByStoreParams) ([]ListWavesByStoreRow, error) {
	rows, err := q.db.Query(ctx, listWavesByStore, arg.OrgID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWavesByStoreRow
	for rows.Next() {
		var i ListWavesByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.Reference,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ListCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startWave = `-- name: StartWave :one
UPDATE waves
SET status = 'picking'
WHERE org_id = $1 AND id = $2 AND status = 'open'
RETURNING id, org_id, store_id, reference, status, created_by, created_at, completed_at
`

type StartWaveParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) StartWave(ctx context.Context, arg StartWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, startWave, arg.OrgID, arg.ID)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Reference,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
