// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zones.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countZonesByStore = `-- name: CountZonesByStore :one
SELECT COUNT(*) FROM zones WHERE store_id = $1 AND org_id = $2
`

type CountZonesByStoreParams struct {
	StoreID uuid.UUID `json:"store_id"`
	OrgID   uuid.UUID `json:"org_id"`
}

func (q *Queries) CountZonesByStore(ctx context.Context, arg CountZonesByStoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, countZonesByStore, arg.StoreID, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createZone = `-- name: CreateZone :one
INSERT INTO zones (org_id, store_id, name, type, x, y, width, height, color, capacity, constraints)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, store_id, name, type, x, y, width, height, color, capacity, constraints, created_at, updated_at
`

type CreateZoneParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	StoreID     uuid.UUID `json:"store_id"`
	Name        string    `json:"name"`
	Type        ZoneType  `json:"type"`
	X           float64   `json:"x"`
	Y           float64   `json:"y"`
	Width       float64   `json:"width"`
	Height      float64   `json:"height"`
	Color       string    `json:"color"`
	Capacity    int32     `json:"capacity"`
	Constraints []byte    `json:"constraints"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.OrgID,
		arg.StoreID,
		arg.Name,
		arg.Type,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.Color,
		arg.Capacity,
		arg.Constraints,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Name,
		&i.Type,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Color,
		&i.Capacity,
		&i.Constraints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteZone = `-- name: DeleteZone :exec
DELETE FROM zones WHERE id = $1 AND org_id = $2
`

type DeleteZoneParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteZone(ctx context.Context, arg DeleteZoneParams) error {
	_, err := q.db.Exec(ctx, deleteZone, arg.ID, arg.OrgID)
	return err
}

const getZone = `-- name: GetZone :one
SELECT id, org_id, store_id, name, type, x, y, width, height, color, capacity, constraints, created_at, updated_at FROM zones WHERE id = $1 AND org_id = $2
`

type GetZoneParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetZone(ctx context.Context, arg GetZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, getZone, arg.ID, arg.OrgID)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Name,
		&i.Type,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Color,
		&i.Capacity,
		&i.Constraints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZonesByStore = `-- name: ListZonesByStore :many
SELECT id, org_id, store_id, name, type, x, y, width, height, color, capacity, constraints, created_at, updated_at FROM zones WHERE store_id = $1 AND org_id = $2 ORDER BY name
`

type ListZonesByStoreParams struct {
	StoreID uuid.UUID `json:"store_id"`
	OrgID   uuid.UUID `json:"org_id"`
}

func (q *Queries) ListZonesByStore(ctx context.Context, arg ListZonesByStoreParams) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZonesByStore, arg.StoreID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.Name,
			&i.Type,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Color,
			&i.Capacity,
			&i.Constraints,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones
SET name        = $3,
    type        = $4,
    x           = $5,
    y           = $6,
    width       = $7,
    height      = $8,
    color       = $9,
    capacity    = $10,
    constraints = $11
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, store_id, name, type, x, y, width, height, color, capacity, constraints, created_at, updated_at
`

type UpdateZoneParams struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	Type        ZoneType  `json:"type"`
	X           float64   `json:"x"`
	Y           float64   `json:"y"`
	Width       float64   `json:"width"`
	Height      float64   `json:"height"`
	Color       string    `json:"color"`
	Capacity    int32     `json:"capacity"`
	Constraints []byte    `json:"constraints"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.Color,
		arg.Capacity,
		arg.Constraints,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Name,
		&i.Type,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Color,
		&i.Capacity,
		&i.Constraints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
